name: ice_cream
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    google_fonts: ^6.1.0
    google_nav_bar: ^5.0.6
    glass_kit: ^3.0.0
    curved_navigation_bar: ^1.0.3
    provider:

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - lib/images/
